-------------------- Log Start | Mon Mar 17 18:52:57 2025 --------------------
data_path: /home/om/printer_data
is_default_data_path: False
config_file: /home/om/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 3060fe1b3f574a95a5a343c6fc66396c
unix_socket_path: /home/om/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/om/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

#################################################################
All Configuration Files:
/home/om/printer_data/config/moonraker.conf
#################################################################

Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 48

System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: 10000000f1b1a7a1
  hardware_desc: BCM2835
  model: Raspberry Pi 4 Model B Rev 1.5
  total_memory: 1713720
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SK32G
  product_revision: 8.5
  serial_number: 83e73683
  manufacturer_date: 6/2024
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['network-online.target', 'system.slice', 'sysinit.target']
**After=['network-online.target', 'system.slice', 'basic.target', 'systemd-journald.socket', 'klipper.service', 'sysinit.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/om/printer_data/systemd/moonraker.env
**ExecStart=/home/om/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=om

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', '-.mount', 'sysinit.target']
**After=['systemd-journald.socket', 'system.slice', 'network-online.target', 'klipper-mcu.service', 'basic.target', '-.mount', 'sysinit.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
Klipper Version: v0.12.0-85-gd785b396a
2025-03-18 00:22:57,889 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 00:22:59,905 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 00:23:01,917 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 00:52:57,888 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 00:52:59,900 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 00:53:01,917 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 01:22:57,892 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 01:22:59,906 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 01:23:01,923 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 01:52:57,893 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 01:52:59,913 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 01:53:01,928 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 02:22:57,894 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 02:22:59,914 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 02:23:01,926 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 02:52:57,888 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 02:52:59,906 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 02:53:01,926 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 03:22:57,894 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 03:22:59,905 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 03:23:01,921 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 03:52:57,891 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 03:52:59,907 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 03:53:01,924 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 04:22:57,900 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 04:22:59,916 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 04:23:01,929 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 04:52:57,898 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 04:52:59,920 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 04:53:01,933 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 05:22:57,900 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 05:22:59,919 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 05:23:01,935 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 05:52:57,895 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 05:52:59,909 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 05:53:01,926 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 06:22:57,900 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 06:22:59,913 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 06:23:01,925 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 06:52:57,903 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 06:52:59,923 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 06:53:01,934 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 07:22:57,898 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 07:22:59,910 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 07:23:01,931 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 07:52:57,901 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 07:52:59,915 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 07:53:01,929 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 08:22:57,907 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 08:22:59,928 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 08:23:01,950 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 08:52:57,901 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 08:52:59,917 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 08:53:01,934 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 09:22:57,908 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 09:22:59,929 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 09:23:01,948 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 09:52:57,902 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 09:52:59,922 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 09:53:01,937 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 10:22:57,915 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 10:22:59,940 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 10:23:01,956 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 10:46:31,986 [klippy_connection.py:wait()] - Request 'gcode/script' pending: 60.00 seconds
2025-03-18 10:52:57,908 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 10:52:59,930 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 10:53:01,944 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 11:08:11,348 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.7.223
2025-03-18 11:08:11,359 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.7.223
2025-03-18 11:15:48,729 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.7.5
2025-03-18 11:15:48,730 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.91ms
2025-03-18 11:15:48,731 [websockets.py:open()] - Websocket Opened: ID: 547615822512, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:15:48,747 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 11:15:49,038 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: server.files.metadata, Code: -32601, Message: Metadata not available for <CFFFP_YADE BARGE 905x635x4 LH.gcode>
2025-03-18 11:15:50,330 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.44ms
2025-03-18 11:15:50,331 [websockets.py:open()] - Websocket Opened: ID: 547616227536, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:15:50,344 [websockets.py:_handle_identify()] - Websocket 547616227536 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 11:15:50,835 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: server.files.metadata, Code: -32601, Message: Metadata not available for <CFFFP_YADE BARGE 905x635x4 LH.gcode>
2025-03-18 11:15:59,503 [application.py:prepare()] - Upload Request Received from 192.168.7.5
Content-Type: 
2025-03-18 11:15:59,521 [application.py:prepare()] - Upload Request Received from 192.168.7.5
Content-Type: multipart/form-data; boundary=----geckoformboundary58f82209bc0d8d2f65ab4b011bc1e10b
2025-03-18 11:15:59,868 [application.py:post()] - Processing Uploaded File: filament spacer_PLA_15m55s.gcode
2025-03-18 11:16:00,081 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2025-03-18 11:16:00,318 [shell_command.py:_check_proc_success()] - Command (/home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/components/file_manager/metadata.py -p /home/om/printer_data/gcodes -f "filament spacer_PLA_15m55s.gcode") successfully finished
2025-03-18 11:16:00,322 [application.py:log_request()] - 201 POST /server/files/upload (192.168.7.5) [_TRUSTED_USER_] 802.95ms
2025-03-18 11:17:01,003 [klippy_connection.py:wait()] - Request 'gcode/script' pending: 60.00 seconds
2025-03-18 11:25:42,074 [application.py:prepare()] - Upload Request Received from 192.168.7.5
Content-Type: multipart/form-data; boundary=----geckoformboundarye351d0184f3a8872154a48c0d858efce
2025-03-18 11:25:42,430 [application.py:post()] - Processing Uploaded File: 1.0filament spacer_PLA_9m47s.gcode
2025-03-18 11:25:42,649 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2025-03-18 11:25:42,751 [shell_command.py:_check_proc_success()] - Command (/home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/components/file_manager/metadata.py -p /home/om/printer_data/gcodes -f "1.0filament spacer_PLA_9m47s.gcode") successfully finished
2025-03-18 11:25:42,756 [application.py:log_request()] - 201 POST /server/files/upload (192.168.7.5) [_TRUSTED_USER_] 683.25ms
2025-03-18 11:26:17,045 [job_state.py:_status_update()] - Job Started: 1.0filament spacer_PLA_9m47s.gcode
2025-03-18 11:30:30,520 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2025-03-18 11:39:06,493 [application.py:prepare()] - Upload Request Received from 192.168.7.5
Content-Type: 
2025-03-18 11:39:06,511 [application.py:prepare()] - Upload Request Received from 192.168.7.5
Content-Type: multipart/form-data; boundary=----geckoformboundary25f6d5043698d08eff842f502df376e2
2025-03-18 11:39:07,299 [application.py:post()] - Processing Uploaded File: filament spacer_PLA_9m43s.gcode
2025-03-18 11:39:07,525 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2025-03-18 11:39:07,614 [shell_command.py:_check_proc_success()] - Command (/home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/components/file_manager/metadata.py -p /home/om/printer_data/gcodes -f "filament spacer_PLA_9m43s.gcode") successfully finished
2025-03-18 11:39:07,619 [application.py:log_request()] - 201 POST /server/files/upload (192.168.7.5) [_TRUSTED_USER_] 1109.52ms
2025-03-18 11:39:10,402 [job_state.py:_status_update()] - Job Started: filament spacer_PLA_9m43s.gcode
2025-03-18 11:39:45,644 [websockets.py:on_close()] - Websocket Closed: ID: 547616227536 Close Code: None, Close Reason: None, Pong Time Elapsed: 25.30
2025-03-18 11:39:45,655 [websockets.py:on_close()] - Websocket Closed: ID: 547615822512 Close Code: None, Close Reason: None, Pong Time Elapsed: 10.06
2025-03-18 11:40:33,675 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.26ms
2025-03-18 11:40:33,676 [websockets.py:open()] - Websocket Opened: ID: 547616227536, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:40:33,775 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 11:40:39,855 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.73ms
2025-03-18 11:40:39,856 [websockets.py:open()] - Websocket Opened: ID: 547616236976, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:40:41,086 [websockets.py:_handle_identify()] - Websocket 547616236976 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 11:40:41,656 [websockets.py:on_close()] - Websocket Closed: ID: 547616227536 Close Code: None, Close Reason: None, Pong Time Elapsed: 7.98
2025-03-18 11:40:42,610 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.14ms
2025-03-18 11:40:42,610 [websockets.py:open()] - Websocket Opened: ID: 547616257840, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:40:42,704 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 11:41:48,297 [application.py:prepare()] - Upload Request Received from 192.168.7.5
Content-Type: multipart/form-data; boundary=----geckoformboundarycdfb01a83f90a02a943ff70acb2a9458
2025-03-18 11:41:48,531 [application.py:post()] - Processing Uploaded File: filament spacer_PLA_9m43s.gcode
2025-03-18 11:41:48,766 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2025-03-18 11:41:48,901 [shell_command.py:_check_proc_success()] - Command (/home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/components/file_manager/metadata.py -p /home/om/printer_data/gcodes -f "filament spacer_PLA_9m43s.gcode") successfully finished
2025-03-18 11:41:48,905 [application.py:log_request()] - 201 POST /server/files/upload (192.168.7.5) [_TRUSTED_USER_] 609.66ms
2025-03-18 11:41:51,103 [job_state.py:_status_update()] - Job Started: filament spacer_PLA_9m43s.gcode
2025-03-18 11:44:06,592 [websockets.py:on_close()] - Websocket Closed: ID: 547616236976 Close Code: None, Close Reason: None, Pong Time Elapsed: 26.72
2025-03-18 11:44:06,595 [websockets.py:write_to_socket()] - Websocket closed while writing: 547616236976
2025-03-18 11:44:06,614 [websockets.py:on_close()] - Websocket Closed: ID: 547616257840 Close Code: None, Close Reason: None, Pong Time Elapsed: 23.97
2025-03-18 11:44:55,912 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 3.79ms
2025-03-18 11:44:55,913 [websockets.py:open()] - Websocket Opened: ID: 547615814560, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:44:55,960 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 11:44:56,198 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.67ms
2025-03-18 11:44:56,199 [websockets.py:open()] - Websocket Opened: ID: 547616230944, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:44:56,206 [websockets.py:_handle_identify()] - Websocket 547616230944 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 11:44:56,621 [websockets.py:on_close()] - Websocket Closed: ID: 547615814560 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.71
2025-03-18 11:44:56,651 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 7.12ms
2025-03-18 11:44:56,652 [websockets.py:open()] - Websocket Opened: ID: 547615817344, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:44:56,743 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 11:48:43,266 [websockets.py:on_close()] - Websocket Closed: ID: 547616230944 Close Code: None, Close Reason: None, Pong Time Elapsed: 12.35
2025-03-18 11:48:43,269 [websockets.py:on_close()] - Websocket Closed: ID: 547615817344 Close Code: None, Close Reason: None, Pong Time Elapsed: 12.35
2025-03-18 11:49:41,125 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.30ms
2025-03-18 11:49:41,125 [websockets.py:open()] - Websocket Opened: ID: 547651302976, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:49:41,134 [websockets.py:_handle_identify()] - Websocket 547651302976 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 11:49:41,484 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.79ms
2025-03-18 11:49:41,485 [websockets.py:open()] - Websocket Opened: ID: 547616228784, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:49:42,062 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.28ms
2025-03-18 11:49:42,066 [websockets.py:open()] - Websocket Opened: ID: 547616231376, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:49:43,156 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 11:50:40,158 [websockets.py:on_close()] - Websocket Closed: ID: 547651302976 Close Code: None, Close Reason: None, Pong Time Elapsed: 15.40
2025-03-18 11:50:40,186 [websockets.py:on_close()] - Websocket Closed: ID: 547616231376 Close Code: None, Close Reason: None, Pong Time Elapsed: 10.07
2025-03-18 11:50:49,347 [websockets.py:on_close()] - Websocket Closed: ID: 547616228784 Close Code: None, Close Reason: None, Pong Time Elapsed: 19.24
2025-03-18 11:51:29,782 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.46ms
2025-03-18 11:51:29,782 [websockets.py:open()] - Websocket Opened: ID: 547616256448, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:51:29,818 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 11:51:29,836 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.94ms
2025-03-18 11:51:29,837 [websockets.py:open()] - Websocket Opened: ID: 547616230416, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:51:29,867 [websockets.py:_handle_identify()] - Websocket 547616230416 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 11:51:30,273 [websockets.py:on_close()] - Websocket Closed: ID: 547616256448 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.49
2025-03-18 11:51:30,312 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.60ms
2025-03-18 11:51:30,312 [websockets.py:open()] - Websocket Opened: ID: 547650861280, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:51:32,874 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 11:52:30,464 [websockets.py:on_close()] - Websocket Closed: ID: 547616230416 Close Code: None, Close Reason: None, Pong Time Elapsed: 18.21
2025-03-18 11:52:30,493 [websockets.py:on_close()] - Websocket Closed: ID: 547650861280 Close Code: None, Close Reason: None, Pong Time Elapsed: 18.19
2025-03-18 11:53:13,826 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f82977040>, <Task finished name='Task-13091128' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 11:53:17,396 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f8079d700>, <Task finished name='Task-13091274' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 11:53:20,469 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f8079d4c0>, <Task finished name='Task-13091427' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 11:53:30,533 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.99ms
2025-03-18 11:53:30,533 [websockets.py:open()] - Websocket Opened: ID: 547614946496, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:53:30,689 [websockets.py:_handle_identify()] - Websocket 547614946496 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 11:53:30,712 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.47ms
2025-03-18 11:53:30,712 [websockets.py:open()] - Websocket Opened: ID: 547616231232, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:53:31,134 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.55ms
2025-03-18 11:53:31,134 [websockets.py:open()] - Websocket Opened: ID: 547616231088, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 11:53:31,171 [file_manager.py:get_file_list()] - Updating File List <config>...
-------------------- Log Start | Tue Mar 18 06:24:26 2025 --------------------
data_path: /home/om/printer_data
is_default_data_path: False
config_file: /home/om/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 3060fe1b3f574a95a5a343c6fc66396c
unix_socket_path: /home/om/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/om/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False
2025-03-18 11:54:26,743 [confighelper.py:read_file()] - Configuration File '/home/om/printer_data/config/moonraker.conf' parsed, total size: 2196 B
2025-03-18 11:54:26,743 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

#################################################################
All Configuration Files:
/home/om/printer_data/config/moonraker.conf
#################################################################
2025-03-18 11:54:27,030 [server.py:load_component()] - Component (secrets) loaded
2025-03-18 11:54:27,045 [server.py:load_component()] - Component (template) loaded
2025-03-18 11:54:27,053 [server.py:load_component()] - Component (klippy_connection) loaded
2025-03-18 11:54:28,237 [server.py:load_component()] - Component (application) loaded
2025-03-18 11:54:28,274 [server.py:load_component()] - Component (websockets) loaded
2025-03-18 11:54:28,422 [server.py:load_component()] - Component (dbus_manager) loaded
2025-03-18 11:54:28,472 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 49
2025-03-18 11:54:28,488 [server.py:load_component()] - Component (database) loaded
2025-03-18 11:54:28,520 [file_manager.py:__init__()] - Using File System Observer: inotify
2025-03-18 11:54:28,567 [server.py:load_component()] - Component (file_manager) loaded
2025-03-18 11:54:28,573 [server.py:load_component()] - Component (klippy_apis) loaded
2025-03-18 11:54:28,843 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: 10000000f1b1a7a1
  hardware_desc: BCM2835
  model: Raspberry Pi 4 Model B Rev 1.5
  total_memory: 1713720
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SK32G
  product_revision: 8.5
  serial_number: 83e73683
  manufacturer_date: 6/2024
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2025-03-18 11:54:28,846 [server.py:load_component()] - Component (shell_command) loaded
2025-03-18 11:54:28,847 [machine.py:__init__()] - Using System Provider: systemd_dbus
2025-03-18 11:54:28,851 [server.py:load_component()] - Component (machine) loaded
2025-03-18 11:54:28,855 [server.py:load_component()] - Component (data_store) loaded
2025-03-18 11:54:28,862 [proc_stats.py:__init__()] - Detected 'vcgencmd', throttle checking enabled
2025-03-18 11:54:28,863 [server.py:load_component()] - Component (proc_stats) loaded
2025-03-18 11:54:28,865 [server.py:load_component()] - Component (job_state) loaded
2025-03-18 11:54:28,870 [server.py:load_component()] - Component (job_queue) loaded
2025-03-18 11:54:28,881 [server.py:load_component()] - Component (http_client) loaded
2025-03-18 11:54:28,890 [server.py:load_component()] - Component (announcements) loaded
2025-03-18 11:54:28,897 [server.py:load_component()] - Component (webcam) loaded
2025-03-18 11:54:28,903 [server.py:load_component()] - Component (extensions) loaded
2025-03-18 11:54:28,911 [server.py:load_component()] - Component (history) loaded
2025-03-18 11:54:28,945 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
fe80::/10
::1/128
CORS Domains:
https://my\.mainsail\.xyz
http://my\.mainsail\.xyz
http://.*\.local
http://.*\.lan
2025-03-18 11:54:28,950 [server.py:load_component()] - Component (authorization) loaded
2025-03-18 11:54:28,957 [server.py:load_component()] - Component (octoprint_compat) loaded
2025-03-18 11:54:28,960 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2025-03-18 11:54:28,974 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2025-03-18 11:54:28,983 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2025-03-18 11:54:28,984 [machine.py:validation_init()] - Installation version in database up to date
2025-03-18 11:54:29,315 [machine.py:check_virt_status()] - No Virtualization Detected
2025-03-18 11:54:29,331 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.123
2025-03-18 11:54:29,334 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.123
2025-03-18 11:54:29,396 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['network-online.target', 'system.slice', 'sysinit.target']
**After=['network-online.target', 'system.slice', 'systemd-journald.socket', 'sysinit.target', 'klipper.service', 'basic.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/om/printer_data/systemd/moonraker.env
**ExecStart=/home/om/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=om
2025-03-18 11:54:29,396 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2025-03-18 11:54:29,396 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2025-03-18 11:54:29,399 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2025-03-18 11:54:29,400 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.123
2025-03-18 11:54:29,400 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2025-03-18 11:54:29,401 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', '-.mount', 'sysinit.target']
**After=['systemd-journald.socket', 'system.slice', 'network-online.target', 'klipper-mcu.service', 'basic.target', '-.mount', 'sysinit.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-18 11:54:29,401 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2025-03-18 11:54:29,403 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2025-03-18 11:54:29,418 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/om/printer_data/comms/moonraker.sock'
2025-03-18 11:54:29,421 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: Go3D
2025-03-18 11:54:29,424 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2025-03-18 11:54:29,677 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-03-18 11:54:29,755 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'system.slice', 'sysinit.target']
**After=['klipper-mcu.service', '-.mount', 'basic.target', 'sysinit.target', 'systemd-journald.socket', 'network-online.target', 'system.slice']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-18 11:54:30,009 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-85-gd785b396a
2025-03-18 11:54:30,022 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-03-18 11:54:30,023 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-03-18 11:54:30,273 [job_state.py:_handle_started()] - Job state initialized: standby
2025-03-18 11:54:30,531 [klippy_connection.py:_check_ready()] - Klippy ready
2025-03-18 11:54:31,024 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-03-18 11:54:31,814 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-03-18 11:54:31,826 [application.py:log_request()] - 101 GET /websocket?token= (127.0.0.1) [_TRUSTED_USER_] 2.78ms
2025-03-18 11:54:31,827 [websockets.py:open()] - Websocket Opened: ID: 548573039008, Proxied: False, User Agent: , Host Name: 127.0.0.1
2025-03-18 11:54:31,868 [websockets.py:_handle_identify()] - Websocket 548573039008 Client Identified - Name: KlipperScreen, Version: v0.4.5-10-43ad9fc6-dirty, Type: display
2025-03-18 11:54:32,388 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2025-03-18 11:54:49,926 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7fb97f5ca0>, <Task finished name='Task-193' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 11:54:52,995 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7fb97f55e0>, <Task finished name='Task-416' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 11:54:58,501 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7fb87020d0>, <Task finished name='Task-570' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 11:55:04,001 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7fb9897ee0>, <Task finished name='Task-724' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 11:55:09,461 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.123
2025-03-18 11:55:09,504 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7fb8702040>, <Task finished name='Task-877' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 11:55:10,001 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': Timeout while connecting
2025-03-18 11:55:11,480 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7fb9897d30>, <Task finished name='Task-1026' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 11:57:31,732 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.123
2025-03-18 12:00:21,912 [machine.py:_find_public_ip()] - Failed to detect local IP address
2025-03-18 12:00:21,913 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2025-03-18 12:01:11,958 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.7.223
2025-03-18 12:01:11,959 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.7.223
2025-03-18 12:01:15,066 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.7.5
2025-03-18 12:01:15,072 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 7.68ms
2025-03-18 12:01:15,073 [websockets.py:open()] - Websocket Opened: ID: 548554656256, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:01:15,479 [websockets.py:_handle_identify()] - Websocket 548554656256 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 12:01:17,445 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 3.57ms
2025-03-18 12:01:17,446 [websockets.py:open()] - Websocket Opened: ID: 548555188352, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:01:17,534 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 12:01:47,252 [application.py:prepare()] - Upload Request Received from 192.168.7.5
Content-Type: multipart/form-data; boundary=----geckoformboundary7b81ffbffa973cc26b01bb785c85ea09
2025-03-18 12:01:51,095 [application.py:post()] - Processing Uploaded File: filament spacer_PLA_10m34s.gcode
2025-03-18 12:01:51,401 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2025-03-18 12:01:51,518 [shell_command.py:_check_proc_success()] - Command (/home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/components/file_manager/metadata.py -p /home/om/printer_data/gcodes -f "filament spacer_PLA_10m34s.gcode") successfully finished
2025-03-18 12:01:51,523 [application.py:log_request()] - 201 POST /server/files/upload (192.168.7.5) [_TRUSTED_USER_] 4275.47ms
2025-03-18 12:03:24,763 [job_state.py:_status_update()] - Job Started: filament spacer_PLA_10m34s.gcode
2025-03-18 12:04:13,204 [websockets.py:on_close()] - Websocket Closed: ID: 548554656256 Close Code: None, Close Reason: None, Pong Time Elapsed: 17.59
2025-03-18 12:04:13,228 [websockets.py:on_close()] - Websocket Closed: ID: 548555188352 Close Code: None, Close Reason: None, Pong Time Elapsed: 10.16
2025-03-18 12:05:03,979 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.17ms
2025-03-18 12:05:03,980 [websockets.py:open()] - Websocket Opened: ID: 548555220304, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:05:04,002 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.46ms
2025-03-18 12:05:04,003 [websockets.py:open()] - Websocket Opened: ID: 548555222464, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:05:04,009 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 12:05:04,025 [websockets.py:_handle_identify()] - Websocket 548555222464 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 12:05:04,373 [websockets.py:on_close()] - Websocket Closed: ID: 548555220304 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.40
2025-03-18 12:05:04,409 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.63ms
2025-03-18 12:05:04,409 [websockets.py:open()] - Websocket Opened: ID: 548555221072, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:05:04,479 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 12:11:38,885 [websockets.py:on_close()] - Websocket Closed: ID: 548555222464 Close Code: None, Close Reason: None, Pong Time Elapsed: 34.86
2025-03-18 12:11:38,887 [websockets.py:write_to_socket()] - Websocket closed while writing: 548555222464
2025-03-18 12:11:38,949 [websockets.py:on_close()] - Websocket Closed: ID: 548555221072 Close Code: None, Close Reason: None, Pong Time Elapsed: 34.20
2025-03-18 12:12:16,862 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 4.20ms
2025-03-18 12:12:16,863 [websockets.py:open()] - Websocket Opened: ID: 548555220448, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:12:16,897 [websockets.py:_handle_identify()] - Websocket 548555220448 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 12:12:16,907 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 3.49ms
2025-03-18 12:12:16,908 [websockets.py:open()] - Websocket Opened: ID: 548555220304, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:12:17,477 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.35ms
2025-03-18 12:12:17,477 [websockets.py:open()] - Websocket Opened: ID: 548555156400, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:12:17,614 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 12:12:42,769 [websockets.py:on_close()] - Websocket Closed: ID: 548555220448 Close Code: None, Close Reason: None, Pong Time Elapsed: 25.91
2025-03-18 12:12:42,771 [websockets.py:write_to_socket()] - Websocket closed while writing: 548555220448
2025-03-18 12:12:42,802 [websockets.py:on_close()] - Websocket Closed: ID: 548555156400 Close Code: None, Close Reason: None, Pong Time Elapsed: 25.33
2025-03-18 12:12:47,710 [websockets.py:write_to_socket()] - Websocket closed while writing: 548555220304
2025-03-18 12:12:51,910 [websockets.py:on_close()] - Websocket Closed: ID: 548555220304 Close Code: None, Close Reason: None, Pong Time Elapsed: 35.01
2025-03-18 12:13:33,430 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 3.68ms
2025-03-18 12:13:33,431 [websockets.py:open()] - Websocket Opened: ID: 548555148592, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:13:33,494 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 3.36ms
2025-03-18 12:13:33,494 [websockets.py:open()] - Websocket Opened: ID: 548555147152, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:13:33,498 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 12:13:34,241 [websockets.py:_handle_identify()] - Websocket 548555147152 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 12:13:34,710 [websockets.py:on_close()] - Websocket Closed: ID: 548555148592 Close Code: None, Close Reason: None, Pong Time Elapsed: 1.28
2025-03-18 12:13:34,803 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.59ms
2025-03-18 12:13:34,804 [websockets.py:open()] - Websocket Opened: ID: 548555146000, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:13:34,846 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 12:16:46,776 [websockets.py:on_close()] - Websocket Closed: ID: 548555147152 Close Code: None, Close Reason: None, Pong Time Elapsed: 19.59
2025-03-18 12:16:46,796 [websockets.py:on_close()] - Websocket Closed: ID: 548555146000 Close Code: None, Close Reason: None, Pong Time Elapsed: 17.01
2025-03-18 12:17:09,594 [job_state.py:_status_update()] - Job Started: filament spacer_PLA_10m34s.gcode
2025-03-18 12:17:38,716 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 7.21ms
2025-03-18 12:17:38,718 [websockets.py:open()] - Websocket Opened: ID: 548555144208, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:17:38,733 [websockets.py:_handle_identify()] - Websocket 548555144208 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 12:17:38,748 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 3.58ms
2025-03-18 12:17:38,749 [websockets.py:open()] - Websocket Opened: ID: 548555143440, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:17:39,099 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.16ms
2025-03-18 12:17:39,099 [websockets.py:open()] - Websocket Opened: ID: 548555145904, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:17:39,134 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 12:35:04,114 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.7.223
2025-03-18 12:35:29,102 [websockets.py:write_to_socket()] - Websocket closed while writing: 548555145904
2025-03-18 12:35:29,126 [websockets.py:write_to_socket()] - Websocket closed while writing: 548555143440
2025-03-18 12:35:33,719 [websockets.py:on_close()] - Websocket Closed: ID: 548555144208 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.97
2025-03-18 12:35:33,720 [websockets.py:write_to_socket()] - Websocket closed while writing: 548555144208
2025-03-18 12:35:33,750 [websockets.py:on_close()] - Websocket Closed: ID: 548555143440 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.95
2025-03-18 12:35:34,101 [websockets.py:on_close()] - Websocket Closed: ID: 548555145904 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.90
2025-03-18 12:36:41,698 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2025-03-18 12:36:44,214 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.7.223
2025-03-18 12:36:46,661 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.20ms
2025-03-18 12:36:46,661 [websockets.py:open()] - Websocket Opened: ID: 548555103104, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:36:46,679 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 12:36:46,903 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.43ms
2025-03-18 12:36:46,903 [websockets.py:open()] - Websocket Opened: ID: 548555142768, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:36:46,914 [websockets.py:_handle_identify()] - Websocket 548555142768 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 12:36:47,316 [websockets.py:on_close()] - Websocket Closed: ID: 548555103104 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.66
2025-03-18 12:36:47,500 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.54ms
2025-03-18 12:36:47,501 [websockets.py:open()] - Websocket Opened: ID: 548555143632, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 12:36:47,531 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 12:37:28,900 [job_state.py:_status_update()] - Job Started: filament spacer_PLA_10m34s.gcode
2025-03-18 13:00:53,006 [websockets.py:on_close()] - Websocket Closed: ID: 548555143632 Close Code: None, Close Reason: None, Pong Time Elapsed: 19.04
2025-03-18 13:01:10,885 [websockets.py:on_close()] - Websocket Closed: ID: 548555142768 Close Code: None, Close Reason: None, Pong Time Elapsed: 36.97
2025-03-18 13:01:10,887 [websockets.py:write_to_socket()] - Websocket closed while writing: 548555142768
2025-03-18 13:01:41,846 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 2.18ms
2025-03-18 13:01:41,846 [websockets.py:open()] - Websocket Opened: ID: 548555176784, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 13:01:41,911 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 13:01:42,319 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.84ms
2025-03-18 13:01:42,319 [websockets.py:open()] - Websocket Opened: ID: 548555101136, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 13:01:42,355 [websockets.py:_handle_identify()] - Websocket 548555101136 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 13:01:42,803 [websockets.py:on_close()] - Websocket Closed: ID: 548555176784 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.96
2025-03-18 13:01:42,975 [application.py:log_request()] - 101 GET /websocket (192.168.7.5) [_TRUSTED_USER_] 1.60ms
2025-03-18 13:01:42,975 [websockets.py:open()] - Websocket Opened: ID: 548555101616, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0, Host Name: 192.168.7.223
2025-03-18 13:01:43,149 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 13:07:16,153 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.7.223
2025-03-18 13:11:56,159 [job_state.py:_status_update()] - Job Started: filament spacer_PLA_10m34s.gcode
2025-03-18 13:18:08,200 [websockets.py:on_close()] - Websocket Closed: ID: 548555101136 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 4.71
2025-03-18 13:18:08,202 [websockets.py:on_close()] - Websocket Closed: ID: 548555101616 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 3.68
2025-03-18 13:20:16,978 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.7.223
2025-03-18 13:26:43,686 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 13:26:45,706 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 13:26:47,720 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 13:41:41,683 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 127.0.0.1
2025-03-18 13:56:43,682 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 13:56:45,697 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 13:56:47,713 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 14:06:41,687 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.7.5
2025-03-18 14:26:43,698 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 14:26:45,722 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 14:26:47,745 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 14:56:43,701 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 14:56:45,725 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 14:56:47,749 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 15:08:27,970 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2025-03-18 15:11:02,795 [websockets.py:write_to_socket()] - Websocket closed while writing: 548573039008
2025-03-18 15:11:02,796 [websockets.py:on_close()] - Websocket Closed: ID: 548573039008 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.97
2025-03-18 15:11:03,720 [server.py:_handle_term_signal()] - Exiting with signal SIGTERM
2025-03-18 15:11:03,826 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2025-03-18 15:11:03,833 [database.py:close()] - Database statistics:

announcements:
psize: 4096
depth: 0
branch_pages: 0
leaf_pages: 0
overflow_pages: 0
entries: 0
authorized_users:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
gcode_metadata:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 3
history:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 4
overflow_pages: 0
entries: 14
mainsail:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 4
maintenance:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
moonraker:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 7
update_manager:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 8
entries: 7
2025-03-18 15:11:03,837 [server.py:main()] - Server Shutdown
-------------------- Log Start | Tue Mar 18 09:41:17 2025 --------------------
data_path: /home/om/printer_data
is_default_data_path: False
config_file: /home/om/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 3060fe1b3f574a95a5a343c6fc66396c
unix_socket_path: /home/om/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/om/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False
2025-03-18 15:11:17,572 [confighelper.py:read_file()] - Configuration File '/home/om/printer_data/config/moonraker.conf' parsed, total size: 2196 B
2025-03-18 15:11:17,572 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

#################################################################
All Configuration Files:
/home/om/printer_data/config/moonraker.conf
#################################################################
2025-03-18 15:11:17,842 [server.py:load_component()] - Component (secrets) loaded
2025-03-18 15:11:17,858 [server.py:load_component()] - Component (template) loaded
2025-03-18 15:11:17,866 [server.py:load_component()] - Component (klippy_connection) loaded
2025-03-18 15:11:18,935 [server.py:load_component()] - Component (application) loaded
2025-03-18 15:11:18,996 [server.py:load_component()] - Component (websockets) loaded
2025-03-18 15:11:19,190 [server.py:load_component()] - Component (dbus_manager) loaded
2025-03-18 15:11:19,253 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 49
2025-03-18 15:11:19,281 [server.py:load_component()] - Component (database) loaded
2025-03-18 15:11:19,321 [file_manager.py:__init__()] - Using File System Observer: inotify
2025-03-18 15:11:19,367 [server.py:load_component()] - Component (file_manager) loaded
2025-03-18 15:11:19,375 [server.py:load_component()] - Component (klippy_apis) loaded
2025-03-18 15:11:19,655 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: 10000000f1b1a7a1
  hardware_desc: BCM2835
  model: Raspberry Pi 4 Model B Rev 1.5
  total_memory: 1713720
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SK32G
  product_revision: 8.5
  serial_number: 83e73683
  manufacturer_date: 6/2024
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2025-03-18 15:11:19,658 [server.py:load_component()] - Component (shell_command) loaded
2025-03-18 15:11:19,659 [machine.py:__init__()] - Using System Provider: systemd_dbus
2025-03-18 15:11:19,663 [server.py:load_component()] - Component (machine) loaded
2025-03-18 15:11:19,669 [server.py:load_component()] - Component (data_store) loaded
2025-03-18 15:11:19,674 [proc_stats.py:__init__()] - Detected 'vcgencmd', throttle checking enabled
2025-03-18 15:11:19,676 [server.py:load_component()] - Component (proc_stats) loaded
2025-03-18 15:11:19,678 [server.py:load_component()] - Component (job_state) loaded
2025-03-18 15:11:19,685 [server.py:load_component()] - Component (job_queue) loaded
2025-03-18 15:11:19,698 [server.py:load_component()] - Component (http_client) loaded
2025-03-18 15:11:19,706 [server.py:load_component()] - Component (announcements) loaded
2025-03-18 15:11:19,712 [server.py:load_component()] - Component (webcam) loaded
2025-03-18 15:11:19,716 [server.py:load_component()] - Component (extensions) loaded
2025-03-18 15:11:19,750 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
fe80::/10
::1/128
CORS Domains:
https://my\.mainsail\.xyz
http://my\.mainsail\.xyz
http://.*\.local
http://.*\.lan
2025-03-18 15:11:19,754 [server.py:load_component()] - Component (authorization) loaded
2025-03-18 15:11:19,761 [server.py:load_component()] - Component (history) loaded
2025-03-18 15:11:19,768 [server.py:load_component()] - Component (octoprint_compat) loaded
2025-03-18 15:11:19,770 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2025-03-18 15:11:19,785 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2025-03-18 15:11:19,796 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2025-03-18 15:11:19,796 [machine.py:validation_init()] - Installation version in database up to date
2025-03-18 15:11:20,111 [machine.py:check_virt_status()] - No Virtualization Detected
2025-03-18 15:11:20,191 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['network-online.target', 'sysinit.target', 'system.slice']
**After=['klipper.service', 'network-online.target', 'sysinit.target', 'system.slice', 'systemd-journald.socket', 'basic.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/om/printer_data/systemd/moonraker.env
**ExecStart=/home/om/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=om
2025-03-18 15:11:20,192 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2025-03-18 15:11:20,192 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2025-03-18 15:11:20,195 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2025-03-18 15:11:20,196 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2025-03-18 15:11:20,197 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'system.slice', 'sysinit.target']
**After=['klipper-mcu.service', '-.mount', 'basic.target', 'sysinit.target', 'systemd-journald.socket', 'network-online.target', 'system.slice']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-18 15:11:20,198 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2025-03-18 15:11:20,198 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2025-03-18 15:11:20,231 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/om/printer_data/comms/moonraker.sock'
2025-03-18 15:11:20,233 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: Go3D
2025-03-18 15:11:20,235 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2025-03-18 15:11:20,498 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-03-18 15:11:20,558 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', '-.mount', 'sysinit.target']
**After=['sysinit.target', 'system.slice', 'systemd-journald.socket', '-.mount', 'network-online.target', 'klipper-mcu.service', 'basic.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-18 15:11:20,812 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-85-gd785b396a
2025-03-18 15:11:20,834 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-03-18 15:11:20,837 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-03-18 15:11:21,085 [job_state.py:_handle_started()] - Job state initialized: standby
2025-03-18 15:11:21,342 [klippy_connection.py:_check_ready()] - Klippy ready
2025-03-18 15:11:21,837 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-03-18 15:11:22,250 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 15:11:22,905 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-03-18 15:11:22,915 [application.py:log_request()] - 101 GET /websocket?token= (127.0.0.1) [_TRUSTED_USER_] 2.53ms
2025-03-18 15:11:22,916 [websockets.py:open()] - Websocket Opened: ID: 547913547296, Proxied: False, User Agent: , Host Name: 127.0.0.1
2025-03-18 15:11:22,952 [websockets.py:_handle_identify()] - Websocket 547913547296 Client Identified - Name: KlipperScreen, Version: v0.4.5-10-43ad9fc6-dirty, Type: display
2025-03-18 15:11:23,449 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2025-03-18 15:11:24,262 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 15:11:26,278 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 15:12:20,288 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.123
2025-03-18 15:12:20,291 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.123
2025-03-18 15:14:31,023 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.105
2025-03-18 15:14:31,031 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 11.10ms
2025-03-18 15:14:31,032 [websockets.py:open()] - Websocket Opened: ID: 547877639696, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:14:34,803 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:15:01,028 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 4.01ms
2025-03-18 15:15:01,028 [websockets.py:open()] - Websocket Opened: ID: 547912317152, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:15:01,247 [websockets.py:_handle_identify()] - Websocket 547912317152 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 15:17:02,710 [websockets.py:on_close()] - Websocket Closed: ID: 547912317152 Close Code: None, Close Reason: None, Pong Time Elapsed: 11.12
2025-03-18 15:17:03,107 [websockets.py:on_close()] - Websocket Closed: ID: 547877639696 Close Code: None, Close Reason: None, Pong Time Elapsed: 2.02
2025-03-18 15:17:04,021 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 6.09ms
2025-03-18 15:17:04,022 [websockets.py:open()] - Websocket Opened: ID: 547877666480, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:17:04,707 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:17:13,704 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 2.62ms
2025-03-18 15:17:13,704 [websockets.py:open()] - Websocket Opened: ID: 547877676320, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:17:14,706 [websockets.py:_handle_identify()] - Websocket 547877676320 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 15:17:16,088 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 5.29ms
2025-03-18 15:17:16,089 [websockets.py:open()] - Websocket Opened: ID: 547877650496, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:17:16,228 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:17:16,488 [websockets.py:on_close()] - Websocket Closed: ID: 547877666480 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.00
2025-03-18 15:18:29,718 [websockets.py:on_close()] - Websocket Closed: ID: 547877676320 Close Code: None, Close Reason: None, Pong Time Elapsed: 25.91
2025-03-18 15:18:29,931 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 3.89ms
2025-03-18 15:18:29,932 [websockets.py:open()] - Websocket Opened: ID: 547877655168, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:18:30,531 [websockets.py:on_close()] - Websocket Closed: ID: 547877650496 Close Code: None, Close Reason: None, Pong Time Elapsed: 3.32
2025-03-18 15:18:32,899 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:19:34,116 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 6.21ms
2025-03-18 15:19:34,117 [websockets.py:open()] - Websocket Opened: ID: 547877657136, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:19:37,008 [websockets.py:_handle_identify()] - Websocket 547877657136 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 15:19:40,912 [websockets.py:on_close()] - Websocket Closed: ID: 547877655168 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.00
2025-03-18 15:19:41,629 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 2.92ms
2025-03-18 15:19:41,630 [websockets.py:open()] - Websocket Opened: ID: 547877657280, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:19:43,627 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:20:12,072 [websockets.py:write_to_socket()] - Websocket closed while writing: 547877657280
2025-03-18 15:20:16,634 [websockets.py:on_close()] - Websocket Closed: ID: 547877657280 Close Code: None, Close Reason: None, Pong Time Elapsed: 35.01
2025-03-18 15:21:02,563 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 4.36ms
2025-03-18 15:21:02,564 [websockets.py:open()] - Websocket Opened: ID: 547877656608, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:21:06,150 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:21:32,619 [websockets.py:write_to_socket()] - Websocket closed while writing: 547877656608
2025-03-18 15:21:37,567 [websockets.py:on_close()] - Websocket Closed: ID: 547877656608 Close Code: None, Close Reason: None, Pong Time Elapsed: 35.01
2025-03-18 15:22:10,483 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 5.82ms
2025-03-18 15:22:10,484 [websockets.py:open()] - Websocket Opened: ID: 547877664752, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:22:22,533 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:22:43,048 [websockets.py:on_close()] - Websocket Closed: ID: 547877657136 Close Code: None, Close Reason: None, Pong Time Elapsed: 17.71
2025-03-18 15:22:43,100 [websockets.py:on_close()] - Websocket Closed: ID: 547877664752 Close Code: None, Close Reason: None, Pong Time Elapsed: 20.53
2025-03-18 15:23:45,071 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 5.70ms
2025-03-18 15:23:45,073 [websockets.py:open()] - Websocket Opened: ID: 547877665568, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:23:45,096 [websockets.py:_handle_identify()] - Websocket 547877665568 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 15:23:48,330 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 3.43ms
2025-03-18 15:23:48,331 [websockets.py:open()] - Websocket Opened: ID: 547877665760, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:23:51,470 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:24:45,074 [websockets.py:on_close()] - Websocket Closed: ID: 547877665568 Close Code: None, Close Reason: None, Pong Time Elapsed: 17.92
2025-03-18 15:24:45,145 [websockets.py:on_close()] - Websocket Closed: ID: 547877665760 Close Code: None, Close Reason: None, Pong Time Elapsed: 4.67
2025-03-18 15:24:46,304 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 3.67ms
2025-03-18 15:24:46,304 [websockets.py:open()] - Websocket Opened: ID: 547877703200, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:24:49,165 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:33:46,398 [websockets.py:write_to_socket()] - Websocket closed while writing: 547877703200
2025-03-18 15:33:51,308 [websockets.py:on_close()] - Websocket Closed: ID: 547877703200 Close Code: None, Close Reason: None, Pong Time Elapsed: 43.73
2025-03-18 15:34:20,115 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 3.94ms
2025-03-18 15:34:20,115 [websockets.py:open()] - Websocket Opened: ID: 547877700944, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:34:20,226 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:38:10,230 [websockets.py:write_to_socket()] - Websocket closed while writing: 547877700944
2025-03-18 15:38:15,119 [websockets.py:on_close()] - Websocket Closed: ID: 547877700944 Close Code: None, Close Reason: None, Pong Time Elapsed: 41.79
2025-03-18 15:38:56,162 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 5.72ms
2025-03-18 15:38:56,164 [websockets.py:open()] - Websocket Opened: ID: 547877702912, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:38:56,295 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:40:51,167 [websockets.py:on_close()] - Websocket Closed: ID: 547877702912 Close Code: None, Close Reason: None, Pong Time Elapsed: 39.54
2025-03-18 15:40:51,170 [websockets.py:write_to_socket()] - Websocket closed while writing: 547877702912
2025-03-18 15:41:28,234 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 4.06ms
2025-03-18 15:41:28,235 [websockets.py:open()] - Websocket Opened: ID: 547877701088, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:41:28,698 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:42:00,430 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': Timeout while connecting
2025-03-18 15:42:10,438 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f90085670>, <Task finished name='Task-65360' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 15:42:21,448 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f90085ca0>, <Task finished name='Task-65760' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 15:42:27,444 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': Timeout while connecting
2025-03-18 15:42:31,956 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f7efd6dc0>, <Task finished name='Task-65965' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 15:42:32,452 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f900850d0>, <Task finished name='Task-66159' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 15:42:37,459 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f7efee280>, <Task finished name='Task-66344' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 15:42:42,958 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f900855e0>, <Task finished name='Task-66545' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 15:42:48,464 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f7efd6f70>, <Task finished name='Task-66744' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 15:42:53,238 [websockets.py:on_close()] - Websocket Closed: ID: 547877701088 Close Code: None, Close Reason: None, Pong Time Elapsed: 42.52
2025-03-18 15:42:53,239 [websockets.py:write_to_socket()] - Websocket closed while writing: 547877701088
2025-03-18 15:42:53,967 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f90085790>, <Task finished name='Task-66926' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 15:42:54,459 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': Timeout while connecting
2025-03-18 15:42:59,469 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f7efd6ee0>, <Task finished name='Task-67072' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 269, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2025-03-18 15:43:31,716 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 5.44ms
2025-03-18 15:43:31,717 [websockets.py:open()] - Websocket Opened: ID: 547877702528, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:43:32,592 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:44:01,836 [websockets.py:write_to_socket()] - Websocket closed while writing: 547877702528
2025-03-18 15:44:06,720 [websockets.py:on_close()] - Websocket Closed: ID: 547877702528 Close Code: None, Close Reason: None, Pong Time Elapsed: 35.01
2025-03-18 15:46:05,451 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 5.65ms
2025-03-18 15:46:05,452 [websockets.py:open()] - Websocket Opened: ID: 547877705280, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 15:46:05,755 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 15:47:25,490 [websockets.py:write_to_socket()] - Websocket closed while writing: 547877705280
2025-03-18 15:47:30,456 [websockets.py:on_close()] - Websocket Closed: ID: 547877705280 Close Code: None, Close Reason: None, Pong Time Elapsed: 1.00
2025-03-18 15:55:06,496 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.123
2025-03-18 16:11:33,425 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 127.0.0.1
2025-03-18 16:11:35,433 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 16:11:37,454 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 16:11:39,476 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 16:41:35,445 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 16:41:37,468 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 16:41:39,488 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-18 16:46:33,433 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.105
2025-03-18 17:11:35,439 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-18 17:11:37,462 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-18 17:11:39,485 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
-------------------- Log Start | Tue Mar 18 11:47:29 2025 --------------------
data_path: /home/om/printer_data
is_default_data_path: False
config_file: /home/om/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 3060fe1b3f574a95a5a343c6fc66396c
unix_socket_path: /home/om/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/om/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False
2025-03-18 17:17:29,395 [confighelper.py:read_file()] - Configuration File '/home/om/printer_data/config/moonraker.conf' parsed, total size: 2196 B
2025-03-18 17:17:29,395 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

#################################################################
All Configuration Files:
/home/om/printer_data/config/moonraker.conf
#################################################################
2025-03-18 17:17:29,728 [server.py:load_component()] - Component (secrets) loaded
2025-03-18 17:17:29,743 [server.py:load_component()] - Component (template) loaded
2025-03-18 17:17:29,750 [server.py:load_component()] - Component (klippy_connection) loaded
2025-03-18 17:17:30,965 [server.py:load_component()] - Component (application) loaded
2025-03-18 17:17:31,022 [server.py:load_component()] - Component (websockets) loaded
2025-03-18 17:17:31,201 [server.py:load_component()] - Component (dbus_manager) loaded
2025-03-18 17:17:31,246 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 50
2025-03-18 17:17:31,289 [server.py:load_component()] - Component (database) loaded
2025-03-18 17:17:31,324 [file_manager.py:__init__()] - Using File System Observer: inotify
2025-03-18 17:17:31,367 [server.py:load_component()] - Component (file_manager) loaded
2025-03-18 17:17:31,374 [server.py:load_component()] - Component (klippy_apis) loaded
2025-03-18 17:17:31,634 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: 10000000f1b1a7a1
  hardware_desc: BCM2835
  model: Raspberry Pi 4 Model B Rev 1.5
  total_memory: 1713720
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SK32G
  product_revision: 8.5
  serial_number: 83e73683
  manufacturer_date: 6/2024
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2025-03-18 17:17:31,645 [server.py:load_component()] - Component (shell_command) loaded
2025-03-18 17:17:31,645 [machine.py:__init__()] - Using System Provider: systemd_dbus
2025-03-18 17:17:31,653 [server.py:load_component()] - Component (machine) loaded
2025-03-18 17:17:31,657 [server.py:load_component()] - Component (data_store) loaded
2025-03-18 17:17:31,664 [proc_stats.py:__init__()] - Detected 'vcgencmd', throttle checking enabled
2025-03-18 17:17:31,665 [server.py:load_component()] - Component (proc_stats) loaded
2025-03-18 17:17:31,667 [server.py:load_component()] - Component (job_state) loaded
2025-03-18 17:17:31,673 [server.py:load_component()] - Component (job_queue) loaded
2025-03-18 17:17:31,688 [server.py:load_component()] - Component (http_client) loaded
2025-03-18 17:17:31,697 [server.py:load_component()] - Component (announcements) loaded
2025-03-18 17:17:31,702 [server.py:load_component()] - Component (webcam) loaded
2025-03-18 17:17:31,706 [server.py:load_component()] - Component (extensions) loaded
2025-03-18 17:17:31,712 [server.py:load_component()] - Component (history) loaded
2025-03-18 17:17:31,719 [server.py:load_component()] - Component (octoprint_compat) loaded
2025-03-18 17:17:31,752 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
fe80::/10
::1/128
CORS Domains:
https://my\.mainsail\.xyz
http://my\.mainsail\.xyz
http://.*\.local
http://.*\.lan
2025-03-18 17:17:31,757 [server.py:load_component()] - Component (authorization) loaded
2025-03-18 17:17:31,759 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2025-03-18 17:17:31,775 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2025-03-18 17:17:31,784 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2025-03-18 17:17:31,785 [machine.py:validation_init()] - Installation version in database up to date
2025-03-18 17:17:32,130 [machine.py:check_virt_status()] - No Virtualization Detected
2025-03-18 17:17:32,152 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.123
2025-03-18 17:17:32,156 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.123
2025-03-18 17:17:32,225 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['network-online.target', 'system.slice', 'sysinit.target']
**After=['network-online.target', 'system.slice', 'sysinit.target', 'klipper.service', 'systemd-journald.socket', 'basic.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/om/printer_data/systemd/moonraker.env
**ExecStart=/home/om/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=om
2025-03-18 17:17:32,225 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2025-03-18 17:17:32,225 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2025-03-18 17:17:32,229 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2025-03-18 17:17:32,229 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.123
2025-03-18 17:17:32,230 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2025-03-18 17:17:32,232 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', '-.mount', 'sysinit.target']
**After=['sysinit.target', 'system.slice', 'systemd-journald.socket', '-.mount', 'network-online.target', 'klipper-mcu.service', 'basic.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-18 17:17:32,232 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2025-03-18 17:17:32,234 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2025-03-18 17:17:32,246 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/om/printer_data/comms/moonraker.sock'
2025-03-18 17:17:32,248 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: Go3D
2025-03-18 17:17:32,250 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2025-03-18 17:17:32,504 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-03-18 17:17:32,564 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', '-.mount', 'system.slice']
**After=['-.mount', 'system.slice', 'klipper-mcu.service', 'sysinit.target', 'network-online.target', 'basic.target', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-18 17:17:32,818 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-85-gd785b396a
2025-03-18 17:17:32,833 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-03-18 17:17:32,835 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-03-18 17:17:33,084 [job_state.py:_handle_started()] - Job state initialized: standby
2025-03-18 17:17:33,344 [klippy_connection.py:_check_ready()] - Klippy ready
2025-03-18 17:17:33,837 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-03-18 17:17:34,954 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-03-18 17:45:17,796 [application.py:log_request()] - 101 GET /websocket?token= (127.0.0.1) [_TRUSTED_USER_] 2.11ms
2025-03-18 17:45:17,796 [websockets.py:open()] - Websocket Opened: ID: 548189408464, Proxied: False, User Agent: , Host Name: 127.0.0.1
2025-03-18 17:45:17,905 [websockets.py:_handle_identify()] - Websocket 548189408464 Client Identified - Name: KlipperScreen, Version: v0.4.5-10-43ad9fc6-dirty, Type: display
2025-03-18 17:45:18,462 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2025-03-18 18:40:23,708 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.105
2025-03-18 18:40:23,716 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 11.87ms
2025-03-18 18:40:23,717 [websockets.py:open()] - Websocket Opened: ID: 548154121136, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 18:40:23,734 [websockets.py:_handle_identify()] - Websocket 548154121136 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 18:40:28,059 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 2.96ms
2025-03-18 18:40:28,060 [websockets.py:open()] - Websocket Opened: ID: 548154119696, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 18:40:28,130 [file_manager.py:get_file_list()] - Updating File List <config>...
2025-03-18 18:47:58,129 [websockets.py:write_to_socket()] - Websocket closed while writing: 548154119696
2025-03-18 18:48:03,064 [websockets.py:on_close()] - Websocket Closed: ID: 548154119696 Close Code: None, Close Reason: None, Pong Time Elapsed: 43.93
2025-03-18 18:50:15,079 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 127.0.0.1
2025-03-18 19:15:30,485 [websockets.py:on_close()] - Websocket Closed: ID: 548154121136 Close Code: None, Close Reason: None, Pong Time Elapsed: 6.75
2025-03-18 19:15:37,573 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 5.49ms
2025-03-18 19:15:37,574 [websockets.py:open()] - Websocket Opened: ID: 548154150864, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 19:15:37,746 [websockets.py:_handle_identify()] - Websocket 548154150864 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-18 19:15:39,193 [websockets.py:on_close()] - Websocket Closed: ID: 548154150864 Close Code: None, Close Reason: None, Pong Time Elapsed: 1.62
2025-03-18 19:15:39,528 [application.py:log_request()] - 101 GET /websocket (192.168.1.105) [_TRUSTED_USER_] 2.45ms
2025-03-18 19:15:39,529 [websockets.py:open()] - Websocket Opened: ID: 548154141520, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.123
2025-03-18 19:15:39,529 [websockets.py:on_close()] - Websocket Closed: ID: 548154141520 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.00
-------------------- Log Start | Tue Mar 18 13:57:25 2025 --------------------
data_path: /home/om/printer_data
is_default_data_path: False
config_file: /home/om/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 3060fe1b3f574a95a5a343c6fc66396c
unix_socket_path: /home/om/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/om/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False
2025-03-18 19:27:25,728 [confighelper.py:read_file()] - Configuration File '/home/om/printer_data/config/moonraker.conf' parsed, total size: 2196 B
2025-03-18 19:27:25,728 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

#################################################################
All Configuration Files:
/home/om/printer_data/config/moonraker.conf
#################################################################
2025-03-18 19:27:26,032 [server.py:load_component()] - Component (secrets) loaded
2025-03-18 19:27:26,046 [server.py:load_component()] - Component (template) loaded
2025-03-18 19:27:26,056 [server.py:load_component()] - Component (klippy_connection) loaded
2025-03-18 19:27:27,335 [server.py:load_component()] - Component (application) loaded
2025-03-18 19:27:27,379 [server.py:load_component()] - Component (websockets) loaded
2025-03-18 19:27:27,488 [server.py:load_component()] - Component (dbus_manager) loaded
2025-03-18 19:27:27,549 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 51
2025-03-18 19:27:27,580 [server.py:load_component()] - Component (database) loaded
2025-03-18 19:27:27,617 [file_manager.py:__init__()] - Using File System Observer: inotify
2025-03-18 19:27:27,671 [server.py:load_component()] - Component (file_manager) loaded
2025-03-18 19:27:27,680 [server.py:load_component()] - Component (klippy_apis) loaded
2025-03-18 19:27:27,976 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: 10000000f1b1a7a1
  hardware_desc: BCM2835
  model: Raspberry Pi 4 Model B Rev 1.5
  total_memory: 1713720
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SK32G
  product_revision: 8.5
  serial_number: 83e73683
  manufacturer_date: 6/2024
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2025-03-18 19:27:27,980 [server.py:load_component()] - Component (shell_command) loaded
2025-03-18 19:27:27,980 [machine.py:__init__()] - Using System Provider: systemd_dbus
2025-03-18 19:27:27,986 [server.py:load_component()] - Component (machine) loaded
2025-03-18 19:27:27,991 [server.py:load_component()] - Component (data_store) loaded
2025-03-18 19:27:27,995 [proc_stats.py:__init__()] - Detected 'vcgencmd', throttle checking enabled
2025-03-18 19:27:27,996 [server.py:load_component()] - Component (proc_stats) loaded
2025-03-18 19:27:27,998 [server.py:load_component()] - Component (job_state) loaded
2025-03-18 19:27:28,003 [server.py:load_component()] - Component (job_queue) loaded
2025-03-18 19:27:28,013 [server.py:load_component()] - Component (http_client) loaded
2025-03-18 19:27:28,019 [server.py:load_component()] - Component (announcements) loaded
2025-03-18 19:27:28,023 [server.py:load_component()] - Component (webcam) loaded
2025-03-18 19:27:28,026 [server.py:load_component()] - Component (extensions) loaded
2025-03-18 19:27:28,030 [server.py:load_component()] - Component (history) loaded
2025-03-18 19:27:28,036 [server.py:load_component()] - Component (octoprint_compat) loaded
2025-03-18 19:27:28,061 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
fe80::/10
::1/128
CORS Domains:
https://my\.mainsail\.xyz
http://my\.mainsail\.xyz
http://.*\.local
http://.*\.lan
2025-03-18 19:27:28,066 [server.py:load_component()] - Component (authorization) loaded
2025-03-18 19:27:28,068 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2025-03-18 19:27:28,084 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2025-03-18 19:27:28,095 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2025-03-18 19:27:28,095 [machine.py:validation_init()] - Installation version in database up to date
2025-03-18 19:27:28,459 [machine.py:check_virt_status()] - No Virtualization Detected
2025-03-18 19:27:28,480 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.123
2025-03-18 19:27:28,485 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.123
2025-03-18 19:27:28,546 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'network-online.target', 'sysinit.target']
**After=['klipper.service', 'basic.target', 'system.slice', 'systemd-journald.socket', 'network-online.target', 'sysinit.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/om/printer_data/systemd/moonraker.env
**ExecStart=/home/om/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=om
2025-03-18 19:27:28,546 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2025-03-18 19:27:28,546 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2025-03-18 19:27:28,548 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2025-03-18 19:27:28,548 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.123
2025-03-18 19:27:28,549 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2025-03-18 19:27:28,549 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', '-.mount', 'system.slice']
**After=['-.mount', 'system.slice', 'klipper-mcu.service', 'sysinit.target', 'network-online.target', 'basic.target', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-18 19:27:28,550 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2025-03-18 19:27:28,551 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2025-03-18 19:27:28,577 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/om/printer_data/comms/moonraker.sock'
2025-03-18 19:27:28,579 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: Go3D
2025-03-18 19:27:28,580 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2025-03-18 19:27:28,843 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-03-18 19:27:28,938 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', '-.mount', 'sysinit.target']
**After=['-.mount', 'klipper-mcu.service', 'basic.target', 'system.slice', 'systemd-journald.socket', 'network-online.target', 'sysinit.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-18 19:27:29,191 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-85-gd785b396a
2025-03-18 19:27:29,204 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-03-18 19:27:29,206 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-03-18 19:27:29,455 [job_state.py:_handle_started()] - Job state initialized: standby
2025-03-18 19:27:29,715 [klippy_connection.py:_check_ready()] - Klippy ready
2025-03-18 19:27:30,207 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-03-18 19:27:31,204 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-03-18 19:27:31,216 [application.py:log_request()] - 101 GET /websocket?token= (127.0.0.1) [_TRUSTED_USER_] 2.06ms
2025-03-18 19:27:31,217 [websockets.py:open()] - Websocket Opened: ID: 548082399936, Proxied: False, User Agent: , Host Name: 127.0.0.1
2025-03-18 19:27:31,254 [websockets.py:_handle_identify()] - Websocket 548082399936 Client Identified - Name: KlipperScreen, Version: v0.4.5-10-43ad9fc6-dirty, Type: display
2025-03-18 19:27:31,821 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
